name: cuenta_ganado
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.11
  file_picker: ^5.2.5
  share_plus: ^4.0.10
  shared_preferences: ^2.0.15